

class PocztaPolskaSettingsObject(object):
    POCZTA_POLSKA_API_USERNAME = None
    POCZTA_POLSKA_API_PASSWORD = None
    POCZTA_POLSKA_API_SANDBOX_USERNAME = None
    POCZTA_POLSKA_API_SANDBOX_PASSWORD = None